# Generated by Django 6.0 on 2025-12-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='eye_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='hair_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='height',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='character',
            name='mass',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='skin_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='starship',
            name='cargo_capacity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='starship',
            name='cost_in_credits',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='starship',
            name='crew',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='starship',
            name='length',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='starship',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='starship',
            name='max_atmosphering_speed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='starship',
            name='passengers',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='starship',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
